apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabobank-assignment
  name: rabobank-assignment
  namespace: assignment
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: rabobank-assignment
